# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Import Multiple Pics' do
pod 'DKImagePickerController'
pod "BSImagePicker", "~> 2.1"
end

target 'Import Multiple PicsTests' do

end

target 'Import Multiple PicsUITests' do

end

